### ISSUE TITLE
Infografía Actividad 4 Diego Cruz Cruz

### ISSUE THREAD

**Issue by Diegocruz040708** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Diegocruz040708#1]
[Infografía conceptos y funciones de una librería.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Diegocruz040708/files/14582781/Infografia.conceptos.y.funciones.de.una.libreria.DCC.pdf)
Diego Cruz Cruz

**Comment by Diegocruz040708** [comment]
[Infografía conceptos y funciones de una librería DCC.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Diegocruz040708/files/14582797/Infografia.conceptos.y.funciones.de.una.libreria.DCC.pdf)

**Comment by Nancy-0714** [comment]
Calificación 20, pero solo falto los gráficos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
